// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgrasxsdutrgeezlabua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxncmFzeHNkdXRyZ2VlemxhYnVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTI2NTcsImV4cCI6MjA2NzQyODY1N30.EpMa6x4thwr0crAH2GNXihqAOY3xfPLorVvldF7K1L0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});